version: '3.8'
services:
  redis:
    image: redis:7.2-alpine
    container_name: dialogue-hub-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - dialogue-hub-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: dialogue-hub-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - dialogue-hub-network

volumes:
  redis_data:
  rabbitmq_data:

networks:
  dialogue-hub-network:
    driver: bridge